SET(CMAKE_C_COMPILER arm-none-eabi-gcc)
SET(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_PROCESSOR arm)
add_definitions ( -DUSE_HAL_DRIVER )
add_definitions ( -DSTM32F401xC )
set ( CMAKE_C_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -fmessage-length=0 -ffunction-sections -g -gdwarf-2 -O3" )
set ( CMAKE_CXX_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -fmessage-length=0 -ffunction-sections  -fno-exceptions -fno-rtti -g -gdwarf-2 -O3" )
set ( CMAKE_ASM_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -x assembler-with-cpp" )
set ( CMAKE_EXE_LINKER_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft --specs=nano.specs --specs=nosys.specs -T\"${PROJECT_SOURCE_DIR}/STM32F401CCUx_FLASH.ld\" -lc -lm -lnosys -Wl,--gc-sections" )
